task_1: task_1.o
	gcc -Wall -Wextra -pedantic -Wunused-variable -Werror task_1.o -o task_1

task_1.o: task_1.c
	gcc -Wall -Wextra -pedantic -Wunused-variable -Werror -c task_1.c -o task_1.o

clean:
	rm -f task_1 *.o